# Generated by Django 3.2.8 on 2021-10-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apinew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apinew.watchlist'),
        ),
    ]
