# Generated by Django 3.2.8 on 2021-10-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apinew', '0002_auto_20211009_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='apinew.streamplatform'),
            preserve_default=False,
        ),
    ]
